---
- name: Create env file
  become: yes
  assemble: src=/etc/env.d dest=/etc/environment mode=0644
  notify:
    - reload systemd

- name: reload systemd
  become: true
  command: systemctl --system daemon-reload
  notify:
    - restart daemons

- name: restart daemons
  command: /bin/true
  notify:
    - restart kubelet

- name: restart kubelet
  become: true
  service: name=kubelet state=restarted
